Add controllers
Elen-B/java-shareit pull request #1
Opened 2024-08-29 14:54 UTC by Elen-B

Для работы с patch-запросами попробовала применить обертки JsonNullable для полей dto-классов, понимаю, что здесь можно было обойтись просто проверками на null, но было интересно, как реализовывать работу с patch-запросами, если поля могут быть нуллабельные. Какие-то сложности были в регистрации кастомного ValueExtractor, не знаю, можно ли так, как в итоге сделала.

2024-08-29 18:47 UTC, z8q requested changes

2024-08-29 18:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
Модели в последующих домашках станут jpa-сущностями
На них будет функция взаимодействия с базой
Функцию валидации полей (валидация запроса) лучше оставить только на dto

2024-08-29 18:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dto/ItemUpdateDto.java
> +    JsonNullable<@NotNull Boolean> available = JsonNullable.undefined();
Со стоками задумку понял
null значение допускается,
но если значение не null, то валидируем по аннотации NotBlank

с Boolean не совсем понятно,
null значение допускается,
но если значение не null, null не допускается

2024-08-29 18:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemMapper itemMapper;
Маппинг можно было бы перенести в сервис,
для контроллера оставить только логику получения запроса, валидации и отправки ответа

Если бы возникали какие-то ошибки в маппинге, то все в сервисном классе отлавливать

2024-08-29 18:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepositoryImpl.java
> +        if (email == null) {
Увидел в коде использование Optional.ofNullable
Подумал, что можно тут попробовать к такому виду привести
```JAVA
return Optional.ofNullable(email)
        .map(email -> users.values()
                .stream()
                .filter(user -> !Objects.equals(user.getId(), userId))
                .anyMatch(user -> user.getEmail().equalsIgnoreCase(email)))
        .orElse(false);
```

2024-08-30 16:48 UTC, Elen-B commented on src/main/java/ru/practicum/shareit/item/dto/ItemUpdateDto.java
> +    JsonNullable<@NotNull Boolean> available = JsonNullable.undefined();
Задумка была такая:
1. получаем json patch-запроса, в котором указаны все/часть полей из целевой модели данных
2. при десереализации в dto-объект поля, которые перечислены в json, должны валидироваться по указанным над этими полями аннотациям. А поля, которых нет в json, не валидируются, то есть пропускается к примеру требование @NotNull, и в dto у них значение JsonNullable.undefined
3. маппер должен уметь обновлять сервисную модель по dto-объекту по правилам: если в dto значение поля JsonNullable.undefined (то есть его не было в пришедшем Json), то поле сервисной модели не обновляется, в притивном случае - обновляется

Похоже, мой маппер работал неправильно, т.к. JsonNullable.undefined() он принимал за null. Всё дело в том, что не получилось использовать аннотацию @Condition для того, чтобы прописать доп условия для создания маппера с помощью mapstruct. В итоге поняла, что не та версия mapstruct была.
Ну и вторая заминка вышла с тем, что чтобы обновлять что-то сначала надо достать это что-то из базы, а если маппер в контроллере, то доставать из базы там плохо. Перенесла маппинг в сервисный слой, подключила обновление с помощью маппера.
Надеюсь, вторая версия работает лучше.. по крайней мере сгенерированный в target маппер анализирует наличие/отсутствие поля в dto:
   ```
public void update(ItemUpdateDto update, Long itemId, Long userId, Item destination) {
        if (update != null || itemId != null || userId != null) {
            if (update != null) {
                if (this.jsonNullableMapper.isPresent(update.getName())) {
                    destination.setName((String)this.jsonNullableMapper.unwrap(update.getName()));
                }

                if (this.jsonNullableMapper.isPresent(update.getDescription())) {
                    destination.setDescription((String)this.jsonNullableMapper.unwrap(update.getDescription()));
                }

                if (this.jsonNullableMapper.isPresent(update.getAvailable())) {
                    destination.setAvailable((Boolean)this.jsonNullableMapper.unwrap(update.getAvailable()));
                }
            }

            if (itemId != null) {
                destination.setId(itemId);
            }

            if (userId != null) {
                destination.setOwnerId(userId);
            }

        }
    }
```

2024-08-30 18:22 UTC, z8q approved these changes

2024-09-18 15:13 UTC, merged