Add bookings
Elen-B/java-shareit pull request #3
Opened 2024-09-19 17:01 UTC by Elen-B

2024-09-19 19:20 UTC, z8q requested changes

2024-09-19 19:20 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<Comment> comments = commentRepository.findByItemIdIn(items.stream().map(Item::getId).collect(Collectors.toList()));
тут по идее можно было бы сгруппировать в мапу,
где ключ - comment.getItem().getId()
значение - список комментов
чтобы в 101 строке снова stream не создавать

2024-09-20 10:19 UTC, Elen-B commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<Comment> comments = commentRepository.findByItemIdIn(items.stream().map(Item::getId).collect(Collectors.toList()));
Спасибо за рекомендации! Надеюсь, исправила)

2024-09-20 18:47 UTC, z8q approved these changes

2024-09-24 17:18 UTC, merged